apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: app
spec:
  encryptedData:
    PRISMIC_ACCESS_TOKEN: AgB4z2bRS3T3rE7y6eZWNs07EYANLhdM9V+Pipo0aVJy4OappAMAyRdDHgqmk2VWastr9j5ABdfCnG8DDeFKKY/Z9WNQ/u0jVv2RVkv1ffHaMBE12Wjydqyc1C9kQRM+QG0HAhGLN1j6/094pdgLgL6CKPeJxmCiHyf3zIP/ZvMqE6WyYX0YMDGHWThDXZoB1wcmrqQ9G+kh+WupCZO1P5tJbLvlqGgymk6MjYEN9UiNWJ8h4Jm6+59OZZPYUsVl/lylIS2t9c5f8LMhEEKdBQs23QLpWQ0jjACKGFiJscrLHbHrmCZ2g+Xo9Pj7finYAIHBkIKlOdKeRphGmsSw1Txq4mfdCQuUcocjqMqxqu/sDUKLBBLuS0bCsV9NyAR29t9PwK8X3UAQLLErsS7NXN1vmA03oGg7RKwrSuAtERyP/EAImDGQhwmKmyv994VxSjVEkSifHBPxPjf5uoOVFkCb9QE1skSLOqQM7ON47hsMulWdDCi3NTxNB7yEHyk0/ZZDETFaE6SNo/MEQ00jUPNoyPu7km2E4G8dR6zrUbUKozNxt2uQyqQQ9uV/jFIHt7ql9cuXg7+EMc2H/HepysvsFdQLrZonDIritJYQ6orFM18nWbeYDvq39F0niKknfR5vJFXPS4FMCiov2UPijBZEELR+L5svYCM2k2/RdVUi4ubBlW51kAUj7HDA/hoLaodPLiSvVnopYq9nf8/rS5uuJFKk4+V6yZo0kyOr/PqKH2RCi85lBuIEIEzz0w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: app
    type: Opaque
