// This file is generated by Slice Machine. Update with care!

import AboutPeople from './AboutPeople';
import FaqQa from './FaqQa';
import HomeProduct from './HomeProduct';
import ProductDefinition from './ProductDefinition';
import ProductVersions from './ProductVersions';

export {
	AboutPeople,
	FaqQa,
	HomeProduct,
	ProductDefinition,
	ProductVersions,
};

export const components = {
	about_people: AboutPeople,
	faq_qa: FaqQa,
	home_product: HomeProduct,
	product_definition: ProductDefinition,
	product_versions: ProductVersions,
};
