// This file is generated by Slice Machine. Update with care!

import AboutPeople from './AboutPeople';
import DownloadInfos from './DownloadInfos';
import FaqQa from './FaqQa';
import HomeArticleVideo from './HomeArticleVideo';
import HomeProduct from './HomeProduct';
import ProductDefinition from './ProductDefinition';
import ProductVersions from './ProductVersions';

export {
    AboutPeople,
    DownloadInfos,
    FaqQa,
    HomeArticleVideo,
    HomeProduct,
    ProductDefinition,
    ProductVersions,
};

export const components = {
    about_people: AboutPeople,
    download_infos: DownloadInfos,
    faq_qa: FaqQa,
    home_article_video: HomeArticleVideo,
    home_product: HomeProduct,
    product_definition: ProductDefinition,
    product_versions: ProductVersions,
};
