app:
  host: archifiltre.fr
  redirectFrom:
    - "{{ .Values.global.host }}"
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      cpu: 200m
      memory: 1Gi

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          PRODUCTION: true
