app:
  host: archifiltre.fr
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
  redirectFrom:
    - "{{ .Values.global.host }}"
    - archifiltre.fabrique.social.gouv.fr
  autoscale:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          PRODUCTION: true
