app:
  host: archifiltre.fr
  redirectFrom:
    - "{{ .Values.global.host }}"
  autoscale:
    enabled: true
    minReplicas: 1
    maxReplicas: 3

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          PRODUCTION: true
