app:
  host: archifiltre.fr
  redirectFrom:
    - "{{ .Values.global.host }}"
  autoscale:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

jobs:
  runs:
    build-app:
      with:
        buildArgs:
          PRODUCTION: true
