name: Production

on:
  push:
    branches:
      - main
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  follow-deployment:
    uses: SocialGouv/kontinuous/.github/workflows/workflow-logs.yaml@v1
    secrets: inherit
